### ISSUE TITLE
Allow workflow events with no configuration

### ISSUE THREAD

**Issue by jrparish** [ArmaanT/cdkactions#6]
Very cool project!

Perhaps there is a way of doing this, but I will share what we are going for since I don't seem to be able to achieve it. 

Here is the expected config:

```yaml
on:
  push:
    branches:
      - develop
      - release/**
  pull_request:
    # runs on any PR
```

Workflow config I'm attempting to use:

```ts
    const workflow = new Workflow(this, 'test', {
      name: 'Test',
      on: {
        pullRequest: {},
        push: {
          branches: ['develop', 'release/**']
        }
      }
    });
```

Result:

![image](https://user-images.githubusercontent.com/5173987/104216948-58b62f80-5400-11eb-9b54-afb10c0130bb.png)
